//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAFESystem1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseClusterUnit
    {
        public int CourseId { get; set; }
        public int ClusterId { get; set; }
        public int UnitId { get; set; }
    
        public virtual Cluster Cluster { get; set; }
        public virtual Course Course { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
