//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAFESystem1
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentEnrolment
    {
        public int StudentId { get; set; }
        public int EnrolmentId { get; set; }
        public Nullable<System.DateTime> EnrolmentDate { get; set; }
        public int LocationId { get; set; }
        public int SemesterId { get; set; }
        public int CourseId { get; set; }
        public string Status { get; set; }
        public Nullable<int> Fees { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Location Location { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
