//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAFESystem1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TeacherDetails
    {
        public int EnrolmentId { get; set; }
        public string TeacherName { get; set; }
        public string EmploymentType { get; set; }
        public string LocationName { get; set; }
        public string SemesterName { get; set; }
        public string CourseName { get; set; }
        public string CourseType { get; set; }
        public string ClusterName { get; set; }
        public string Status { get; set; }
    }
}
